language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - export TZ='Asia/Beijing'
install:
  - npm install

script:
  - npm run build:travis

after_script:
  - cd ./build
  - git init
  - git config user.name "username"
  - git config user.email "username@163.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/PrettyKing/my-website.git" master:online