name: my-website publish

on:
  push:
    branches:
      - master  # 只在master上push触发部署
    paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: 打包分支
        uses: actions/checkout@v2   # 检出仓库副本
      - name: Node版本 ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 安装依赖
        run: yarn install
      - name: 打包项目
        run: yarn run build
      - name: 添加FTP忽略文件
        run: echo ".*" >> .git-ftp-include
      - name: 上传到服务器部署
        uses: easingthemes/ssh-deploy@v2.1.6
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: './build/' 
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: '/data/' 
          EXCLUDE: "/node_modules/"  
        env:
          CI: true
