name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: actions/checkout版本
        uses: actions/checkout@v2
      - name: Node版本 ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 安装依赖
        run: npm install
      - name: 打包项目
        run: npm run build
      - name: 添加FTP忽略文件
        run: echo ".*" >> .git-ftp-include
      - name: FTP上传到服务器部署
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          local-dir: ./build/
        env:
          CI: true
