name: Publish And Deploy MyWebSite # 自动部署的名称
on:
  push:
    tags: # 当我们提交代码为tag 是以'v'开头的时候才会触发自动部署到服务端 如 git push tag v0.1.0
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境，告诉它运行在什么环境
    steps: 
      - uses: actions/checkout@master
      - name: Git stuff
        run: |
          npm install
          npm run build:travis
          cd ./build
          git init
          git config user.name "chalee"
          git config user.email "chalee695469701@gmail.com"
          git add .
          git commit -m "Action Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://PrettyKing:${{ACCESS_TOKEN}}@github.com/PrettyKing/my-website.git" master:online
